name: Staging Build

on: [ push, pull_request ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build --stacktrace --parallel --exclude-task test
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: astromine-staging
          path: build/libs